# Generated by Django 2.2.3 on 2019-07-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('password', models.CharField(max_length=20, verbose_name='明文密码')),
                ('hash_password', models.CharField(blank=True, max_length=256, null=True, verbose_name='哈希密码')),
            ],
        ),
    ]
